language: node_js
node_js:
  - "8"
services:
  - docker
  - mongodb
before_install:
  - "curl -L https://raw.githubusercontent.com/arunoda/travis-ci-laika/6a3a7afc21be99f1afedbd2856d060a02755de6d/configure.sh | /bin/sh"

before_deploy:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker build --build-arg FONTAWESOMETOKEN=$FONTAWESOMETOKEN -t horizonshadow/famtime .
deploy:
  provider: script
  script: docker push horizonshadow/famtime
  on:
    branch: master