language: node_js
services:
  - docker
before_deploy:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker build --build-arg FONTAWESOMETOKEN=$FONTAWESOMETOKEN -t horizonshadow/famtime .
deploy:
  provider: script
  script: docker push horizonshadow/famtime
  on:
    branch: master